# Comprehensive NGINX-style config test
# Tests all inheritance and validation rules

http {
    # HTTP-level defaults (optional, will be inherited)
   
    # Server 1: Inherits everything from HTTP
    server {
        listen 54;
        listen 127.0.0.189654:8081 ;
        server_name jh; 
        autoindex on ;

        # This server inherits: root, index, client_max_body_size, error_pages, cgi_bin_path
        
        location  /{
        }
        location /api {
            # Override root
            root /var/www/api;
            methods GET POST DELETE;
        }
        
        location /uploads {
            upload on;
            upload_path /var/www/uploads;
            methods POST DELETE;
        }
        
        location /cgi {
            cgi off;
            cgi_ext .py;
        }
    }


    # Server 2: Overrides HTTP defaults
    server {
        listen 80;
        root /var/www/test;  # Override HTTP root
        index test.html;      # Override HTTP index
        client_max_body_size 10M;  # Override HTTP size

        location / {
            methods GET;
        }
        
        location /redirect {
            return 305345341 https://test.local;
        }
    }
    
    # Server 3: Minimal (relies heavily on inheritance)
    server {
        listen 80;
        server_name localhost;
        
        # Inherits root from HTTP
        
        location / {
            root j;
            # Everything inherited
        }}
}{}
