http {
    autoindex on;
        index index.html index.html;
    root /var/www/html;
    cgi_bin_path /usr/bin/python3;
  server {
       root gf;
       listen 8090;
        listen 8090;
       index jkl jkl jk;
       autoindex off;
        server_name jh hkj ;
        location  /{
            cgi off;
            cgi_ext j;
            cgi on;
            autoindex on;
        }
        location /api {
            root /var/www/api;
            index gfd;
            methods GET POST;
        }
        location /uploads {
            autoindex off;
            upload on;
            upload_path /var/www/uploads;
            methods POST DELETE;
        }
        location /cgi {
            cgi off;
            cgi_ext .py;
        }
    }
    server {
        listen 80;
        location / {
            root j;
        }}
}
