# Test missing root (should fail)
http {
    # No root here
    
    server {
        # No root here either - should throw error
        root;
        location / {
            methods GET;
        }
    }
}
