# Test config with HTTP block
http {
  
    
    server {
        listen 127.0.0.1;


        location / {
            methods GET POST;
            index index.php index.html;
            root n;   
        }
        
        location  /uploads {
            methods GET POST DELETE;
            upload off;
            upload_path /var/www/uploads;
            autoindex on;
            root /var/www/html;
        }
        location  /cgi-bin {
            cgi    on;
            cgi_ext .py;
            root /usr/lib/cgi-bin;
            }
    }
    
}
