# Test: Duplicate servers without server_name - Should FAIL
http {
    root /var/www;
    
    server {
        listen 127.0.0.1:80;
        
        location / {
            methods GET;
        }
    }
    
    server {
        listen 127.0.0.1:80;
        
        location / {
            methods GET;
        }
    }
}
