# Test: Duplicate servers (same IP:port:server_name) - Should FAIL
http {
    root /var/www;
    
    server {
        listen 127.0.0.1:80;
        server_name example.com;
        
        location / {
            methods GET;
        }
    }
    server {
        listen 8900;
        server_name example.com;
        
        location / {
            methods GET;
        }
    }
    server {
        listen 127.0.0.1:80;
        server_name example.com;
        
        location / {
            methods GET;
        }
    }
}
