http {
    autoindex on;
    client_max_body_size 0;
        index "index.html" index.html;
    cgi_bin_path "/usr/bin/python3";
    error_page 404 gb;
  server {
       root "g";
       listen 127.0.0.1:8080;
       index "jkl";
       autoindex off;
        server_name diana ;
    }
   server {
    listen 127.0.0.1:80;
       root "html";
        server_name google.com;
       location / {
        root "html";
        index index.html;
    }
   }
}
