http {
    autoindex on;
    client_max_body_size 0;
        index "index.html" index.html;
    cgi_bin_path "/cgi_bin";
    error_page 404 gb;
  server {
       root "www";
       listen 127.0.0.1:8080;
       index "index.html";
       autoindex off;
        server_name diana ;
      location / {
        cgi on;
        cgi_ext py;
        cgi_bin_path /cgi_bin;
      }

      location /a {
        upload on;
        
        upload_path /upload;
      }
    }
}
