# Full test for inheritance
   
    
    server {
         root /http/root;
    index http_index.html;
    client_max_body_size 2048;
    autoindex on;
    cgi_bin_path /usr/lib/cgi-bin;
    error_page 404 /http/404.html;
        listen localhost:8080;
        server_name server1.com;
        root /server1/root;
        
        location /api {
            cgi on;
            cgi_ext .pl;
            methods GET POST;
            root /api/root;
        }
        
        location /inherit {
            methods POST;
        }
    }
    
    