http {
    autoindex on;
    client_max_body_size 0;
        index "index.html" index.html;
    cgi_bin_path "/usr/bin/python3";
    error_page 404 gb;
  server {
    listen "localhost";
       root "g";
       listen "8090";
        listen 8090;
       index "jkl";
       autoindex off;
        server_name jh hkj ;
    }
   server {
    listen 8080;
       root "html";
       location / {
        root "html";
        index index.html;
    }
   }
}
