# import cgi
import os
import sys
from urllib.parse import parse_qs

print("Content-Type: text/html")
print()

method = os.environ.get("REQUEST_METHOD", "GET")
if method == "GET":
    form_data = parse_qs(os.environ.get("QUERY_STRING", ""))
else:
    form_data = parse_qs(sys.stdin.read())
# form_data = parse_qs(sys.stdin.read())

user_name = form_data.get("name", [""])[0]
fav_color = form_data.get("color", [""])[0]

print("<!DOCTYPE html>")
print("<html lang='en'>")
print("<head>")
print("    <meta charset='UTF-8'>")
print("    <title>CGI POST Response</title>")
print("</head>")
print("<body>")

# Check if we received the data we expected.
if user_name and fav_color:
    print(f"    <h1>Hello, {user_name}!</h1>")
    # We use an inline style to visually confirm the color was received.
    print(f"    <p>Your favorite color is: <strong style='color:{fav_color};'>{fav_color}</strong></p>")
    print("    <p>This response was generated by a Python CGI script.</p>")
else:
    # If the data was missing, show an error.
    print("    <h1>Error!</h1>")
    print("    <p>The form was submitted without a 'name' or 'color'.</p>")
    print("    <p>Please send a POST request with 'name' and 'color' fields.</p>")

print("</body>")
print("</html>")